/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jb.test.networktest;

import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jan
 */
class DlgSelIP extends javax.swing.JDialog {

    private Data mData;
    private List<IPentry> mIPentries;
    private IPentry mEntry;

    /**
     * Creates new form DlgSelIP
     */
    DlgSelIP(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        DefaultTableModel lModel;
        int lRow;

        initComponents();
        mData = Data.getInstance();
        mIPentries = mData.xIPentries();
        lModel = new DefaultTableModel() {
            String[] lColumnName = {"Name", "IP", "Port"};

            @Override
            public int getColumnCount() {
                return lColumnName.length;
            }

            @Override
            public String getColumnName(int pIndex) {
                return lColumnName[pIndex];
            }
        };
        lModel.setRowCount(mIPentries.size());
        tblIP.setModel(lModel);
        for (lRow = 0; lRow < mIPentries.size(); lRow++){
            lModel.setValueAt(mIPentries.get(lRow).xName() , lRow, 0);
            lModel.setValueAt(mIPentries.get(lRow).xIP() , lRow, 1);
            lModel.setValueAt(mIPentries.get(lRow).xPort() , lRow, 2);
        }
    }

    IPentry xIPentry(){
        return mEntry;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblIP = new javax.swing.JTable();
        btnSelect = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Select IP address");

        tblIP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Naam", "IP", "Port"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblIP.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tblIP);

        btnSelect.setText("Select");
        btnSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSelect)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSelect)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectActionPerformed
        int lIndex;
        
        if (tblIP.getSelectedRowCount() > 0){
            lIndex = tblIP.getSelectedRow();
            mEntry = mIPentries.get(lIndex);
        } else {
            mEntry = null;
        }
        setVisible(false);
    }//GEN-LAST:event_btnSelectActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSelect;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblIP;
    // End of variables declaration//GEN-END:variables
}
